services:
  db:
    image: postgres:16
    container_name: banco
    restart: always
    environment:
      POSTGRES_DB: projeto
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: luiz0404
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8085:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - project-network
    depends_on:
      - db

  backend:
    image: luizmario/to-do-backend:latest
    ports:
      - "8000:8000"
    networks:
      - project-network
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://backend:luiz0404@db:5432/projeto
      ALLOWED_HOSTS: localhost,127.0.0.1,192.168.0.131
  
  frontend:
    image: luizmario/to-do-frontend:latest
    ports:
      - "8083:8083"
    networks:
      - project-network
    depends_on:
      - backend
    environment:
      VUE_APP_API_URL: http://192.168.0.131:8000/api/v1/

volumes:
  postgres_data:
  pgadmin_data:

networks:
  project-network:
