version: '3.8'

services:
  db:
    image: postgres:16
    container_name: banco
    restart: always
    environment:
      POSTGRES_DB: projeto
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: luiz0404
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8085:80"
    networks:
      - project-network
    depends_on:
      - db

  backend:
    image: luizmario/to-do-backend:latest
    ports:
      - "8000:8000"
    networks:
      - project-network
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://backend:luiz0404@db:5432/projeto

volumes:
  postgres_data:

networks:
  project-network:
