version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_DB: projeto
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: luiz0404
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8085:80"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  backend-network:
